# Generated by Django 4.2.7 on 2023-12-07 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0017_job_qualifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='category',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Placement'), ('2', 'Target')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='priority',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Critical')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='realm',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Placement'), ('2', 'DoD'), ('3', 'Education'), ('4', 'Technology')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='size',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Startup'), ('2', 'Small'), ('3', 'Medium'), ('4', 'Large')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fcapi.company'),
        ),
        migrations.AddField(
            model_name='note',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fcapi.contact'),
        ),
        migrations.AddField(
            model_name='note',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='fcapi.job'),
        ),
        migrations.AddField(
            model_name='note',
            name='priority',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Low'), ('2', 'Medium'), ('3', 'High'), ('4', 'Critical')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='source',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Manual'), ('2', 'System'), ('3', 'Maintenance')], default='0', max_length=50),
        ),
        migrations.AddField(
            model_name='note',
            name='test',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'Manual'), ('2', 'System'), ('3', 'Maintenance')], default='0', max_length=50),
        ),
        migrations.AlterField(
            model_name='company',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
