# Generated by Django 4.2.7 on 2023-12-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fcapi', '0018_company_category_company_priority_company_realm_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='test',
        ),
        migrations.AlterField(
            model_name='company',
            name='realm',
            field=models.CharField(choices=[('0', 'Unknown'), ('1', 'DoD'), ('2', 'Education'), ('3', 'Technology')], default='0', max_length=50),
        ),
    ]
