# Generated by Django 4.2.7 on 2024-01-08 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('fcapi', '0019_remove_note_test_alter_company_realm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='company',
        ),
        migrations.RemoveField(
            model_name='note',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='note',
            name='job',
        ),
        migrations.AddField(
            model_name='note',
            name='content_type',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='note',
            name='object_id',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
